//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMenssageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMenssageException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exception.ResourceMenssageException", typeof(ResourceMenssageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one ingredients..
        /// </summary>
        public static string AT_LEAST_ONE_INGREDIENTES {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_INGREDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At_least_one_instruction..
        /// </summary>
        public static string AT_LEAST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time not suported..
        /// </summary>
        public static string COOKING_TIME_NOT_SUPORTED {
            get {
                return ResourceManager.GetString("COOKING_TIME_NOT_SUPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificult level not suport..
        /// </summary>
        public static string DIFUCULT_LEVEL_NOT_SUPORT {
            get {
                return ResourceManager.GetString("DIFUCULT_LEVEL_NOT_SUPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish type not suported..
        /// </summary>
        public static string DISH_TYPE_NOT_SUPORTED {
            get {
                return ResourceManager.GetString("DISH_TYPE_NOT_SUPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cannot by empaty..
        /// </summary>
        public static string EMAIL_EMPATY {
            get {
                return ResourceManager.GetString("EMAIL_EMPATY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email most be valid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient empty.
        /// </summary>
        public static string INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGREDIENT_EXCEED_LIMIT_CHARACTERS.
        /// </summary>
        public static string INGREDIENT_EXCEED_LIMIT_CHARACTERS {
            get {
                return ResourceManager.GetString("INGREDIENT_EXCEED_LIMIT_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTION_EMPTY.
        /// </summary>
        public static string INSTRUCTION_EMPTY {
            get {
                return ResourceManager.GetString("INSTRUCTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string INVALID_EMAIL_OR_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot by empaty..
        /// </summary>
        public static string NAME_EMPATY {
            get {
                return ResourceManager.GetString("NAME_EMPATY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authentication token..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON_NEGATIVE_INSTRUCTION_STEP.
        /// </summary>
        public static string NON_NEGATIVE_INSTRUCTION_STEP {
            get {
                return ResourceManager.GetString("NON_NEGATIVE_INSTRUCTION_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is diferent.
        /// </summary>
        public static string PASSWOR_IS_DIFERENT {
            get {
                return ResourceManager.GetString("PASSWOR_IS_DIFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be longes then 6 character. .
        /// </summary>
        public static string PASSWORD_EMPATY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPATY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipy title empty..
        /// </summary>
        public static string RECIPY_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPY_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO_OR_MORE_INSTRUCTIONS_SAME_ORDER.
        /// </summary>
        public static string TWO_OR_MORE_INSTRUCTIONS_SAME_ORDER {
            get {
                return ResourceManager.GetString("TWO_OR_MORE_INSTRUCTIONS_SAME_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User withoute permission acces resource..
        /// </summary>
        public static string USER_WITHOUTE_PERMISSION_ACCES_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUTE_PERMISSION_ACCES_RESOURCE", resourceCulture);
            }
        }
    }
}
